import { Geist, Geist_Mono, Raleway } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import HeaderNavBar from "@/components/HeaderNavBar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const raleway = Raleway({subsets: ['latin']});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={raleway.className}
      >
        <Provider>
          <HeaderNavBar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
